<template>
  <div class="modal modal-open">
    <div class="modal-box">
      <h3 class="font-bold text-lg">Request User Certificate</h3>
      <p class="py-4 text-sm opacity-70">Generate a new X.509 certificate for your user account. You must set a passphrase to protect your private key.</p>
      
      <!-- Error Message -->
      <div v-if="errorMessage" class="alert alert-error mb-4">
        <div class="flex flex-col gap-2">
          <div class="font-bold">{{ errorMessage }}</div>
          <div v-if="existingCert" class="text-sm">
            <p><strong>Existing Certificate:</strong> {{ existingCert.label }}</p>
            <p><strong>Valid Until:</strong> {{ formatDate(existingCert.valid_to) }}</p>
          </div>
        </div>
      </div>
      
      <form @submit.prevent="submit">
        <!-- User Info Readonly -->
        <div class="form-control w-full" v-if="$page.props.auth?.user">
            <label class="label"><span class="label-text">Identity</span></label>
            <input type="text" :value="$page.props.auth.user.name + ' (' + $page.props.auth.user.email + ')'" disabled class="input input-bordered w-full" />
        </div>

        <div class="form-control w-full mt-2">
          <label class="label"><span class="label-text">Certificate Name / Label</span></label>
          <input v-model="form.label" type="text" placeholder="e.g. Finance, Director, Daily" class="input input-bordered w-full" required />
          <label class="label text-xs opacity-50">This name will be used to identify your signature identity in the dropdown.</label>
          <label class="label text-error" v-if="form.errors.label"><span class="label-text-alt">{{ form.errors.label }}</span></label>
        </div>

        <div class="modal-action">
          <button type="button" class="btn" @click="$emit('close')">Cancel</button>
          <button type="submit" class="btn btn-primary" :disabled="form.processing">Generate Certificate</button>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup>
import { useForm, usePage } from '@inertiajs/vue3';
import { ref, onMounted } from 'vue';
import dayjs from 'dayjs';

const emit = defineEmits(['close']);
const page = usePage();

// Get user ID from the auth prop passed by controller
const userId = page.props.auth?.user?.id || null;

const errorMessage = ref('');
const existingCert = ref(null);

const form = useForm({
  label: '',
  user_id: userId,
});

const formatDate = (date) => dayjs(date).format('DD MMM YYYY');

let mainStore = null;

onMounted(async () => {
  try {
    const { useMainStore } = await import('../../../stores');
    mainStore = useMainStore();
  } catch (error) {
    console.error('Failed to load mainStore:', error);
  }
});

const submit = async () => {
    if (!mainStore) {
        errorMessage.value = 'System not ready, please try again.';
        return;
    }

    // Passphrase is auto-generated by backend based on user ID and tenant ID
    const pathParts = window.location.pathname.split('/');
    const tenantSlug = pathParts[1];
    
    const payload = {
        label: form.label,
        user_id: form.user_id
    };
    
    try {
        const response = await mainStore.useAPI(
            `${tenantSlug}/api/digital-signature/certificates`,
            {
                method: 'POST',
                body: payload
            },
            true
        );

        if (response.status === 201 || response.status === 200 || response.code === 201 || response.status === 'success') {
            // Success
            form.reset();
            errorMessage.value = '';
            existingCert.value = null;
            emit('close');
            // Reload page to show new certificate
            window.location.reload();
        } else {
            // Error response
            errorMessage.value = response.message || 'Failed to create certificate';
            existingCert.value = response.existing_certificate || null;
        }
    } catch (error) {
        errorMessage.value = 'An error occurred: ' + (error.response?.message || error.message);
        existingCert.value = error.response?.existing_certificate || null;
    }
};
</script>
